### ISSUE TITLE
Improve, Improve, Improve! :)

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/librepcb-website#1]
The website is still very poor. We should put much more information on it...
- [ ] List all "killer-features" of LibrePCB (with description and screenshots/videos).
- [ ] List import/export file formats
- [ ] Add FAQ
  - [ ] Why not contributing to KiCad?
  - [ ] Why should I use LibrePCB instead of KiCad?
- [ ] Add contact information
- [x] Add a "sponsors" section where we can put all logos of our sponsors.
- [ ] ~Add a Flattr donation button~
- [x] Add a Patreon donation button
- [x] Start writing a blog.

**Comment by dbrgn** [comment]
I'm not sure about Flattr. But you could try https://www.patreon.com/?

**Comment by ubruhin** [comment]
https://www.patreon.com/librepcb

Woohoo! :smiley:
