### ISSUE TITLE
Rename repository to librepcb-website

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/librepcb-website#46]
We don't use GitHub Pages anymore (for a long time) to host our website. So there is no more need to name the repository `LibrePCB.github.io`. Therefore I suggest to rename it to `librepcb-website` for consistency with our other repositories names.

I just realized that the website is even still available at LibrePCB.github.io (without HTTPS) :sob: We should really delete that website...

If there are no objections, I'll do that soon.

**Comment by dbrgn** [comment]
Alternatively, `librepcb.org`. But `librepcb-website` is fine as well.
