### ISSUE TITLE
Libre PCB Board Designer

### ISSUE THREAD

**Issue by jv1597** [LibrePCB/librepcb-website#89]
Hello, I would like to know how to proceed to get a components listing for use with designing a PCB layout for the schematic I have drawn up.  After getting my circuit drawn up on the schematic capture module and go to the PCB designer, it brings up most of the components I'm using on the schematic, but not all of them.  It won't bring up any of the switch components I happen to be using for my circuit.  How do I get a component listing to drag-n-drop from to design my PCB?  Is there a path definitions or options screen I can use to set a path to bring up third-party components?  Thanks in advance.
Jacob

**Comment by ubruhin** [comment]
Hi,
There's nothing to be configured, by default all components from the schematic show up in the "Place Devices" dock in the board editor. The only way to hide something from this list is to enable the "Schematic-Only" checkbox of the component (in the library editor). So make sure this is not checked in your component. If that was not the problem, please share more details (screenshot, project file, ...).

Btw, this issue tracker is for our website :wink: Next time please use the forum: https://librepcb.discourse.group/

**Comment by jv1597** [comment]
Hello, thanks for getting back to me.  I have attached a screenshot of the messages I get.  I get the same message for every switch component on the list.  As you can see, the other components were added to the board, but the switch components say there are no such components in the library.  I'd like to know how to get the library working.  I've even tried going into 'Library Manager' and installing the complete listing of libraries provided to no avail.  ??

**Comment by jv1597** [comment]
Here is a screenshot of the page I get sent to by the link on the board designer...
[Link Page Screenshot.pdf](https://github.com/user-attachments/files/18252127/Link.Page.Screenshot.pdf)

**Comment by ubruhin** [comment]
Ok that's a different case to what you described above as the component *is* listed in the dock :wink: Only the dropdown does not provide any device to choose.

Sad the link is broken, I will correct it. The correct link is here, which should explain what you have to do: https://librepcb.org/faq/#error-no-dev-or-pkg-found

**Comment by jv1597** [comment]
I tried what the FAQ suggested, but it didn't make any difference... I've attached a screenshot of the 'Library Manager' to show that it was done from the list of components, but it still didn't import anything.  It says "scanning xx%" but it doesn't seem to import anything from any of the libraries.
[Library Manager Screenshot.pdf](https://github.com/user-attachments/files/18252266/Library.Manager.Screenshot.pdf)

**Comment by ubruhin** [comment]
Your library only contains a component, but no device. You have to create a device for it: https://librepcb.org/docs/quickstart/create-library-elements/device/

**Comment by jv1597** [comment]
This is what I have so far...
![image](https://github.com/user-attachments/assets/62624102-ece3-48bb-9395-64b756923ce9)

This is the error message I get when using the 'Auto-Add All' button...
![image](https://github.com/user-attachments/assets/49c4e96a-925f-4403-806d-b7a42e549d76)

**Comment by ubruhin** [comment]
If you want the C&K switch, why you don't just install the C&K library? It's so easy.
![Peek 2024-12-27 11-37](https://github.com/user-attachments/assets/7e13ed87-a0fe-492b-b6af-5a6764b34584)

If you want any other switch, please follow the tutorial linked above and it will work fine too.

**Comment by jv1597** [comment]
Well, I tried everything you suggested, but it didn't work...  I have yet to find an ECAD platform structured simplistically enough to be of any good use other than KiCAD.  So I came up with a new take on ECAD recently, incase you're interested.  I called it Easy ECAD.  

Schematic Capture Module:
It entails a simple interface for schematic capture and PCB layout/design.  The schematic capture module comprises a simple grid (zoomable) and a simple standard component library -- containing standard electronics component symbols, no specific model numbers for any (ie: the symbol for a resistor is just a standard symbol for resistor; for microchips all you need is standard symbol for chips (ie: a square or rectangle with pins) consisting of the corresponding number of pins you need to match the chip you'll be using for the circuit).  You can drag and drop the components directly from the component library located to the right of the grid.  The components can be rotated 90 degrees counter-clockwise.  You have the option to change lead line color, grid line color, and grid type (dot/line).  The background of the drawspace is not changeable.  The theme options for the app are light and dark.  Lead lines can connect to other lines and to component pins.  It's that simple... ;)

PCB Board Designer Module:
Same as above but with industry footprint importing, layering, and Gerber plotting capabilities.  Footprints can be imported from component retailers or registrars such as 'ComponentSearchEngine.com'.  Lead lines and components of the layer in focus dim out all other lead lines and components on the board.  Layers can be tabbed to be viewed as separate workspaces.  Via attributes are modifiable (thru-hole, staggered, stacked, buried, and blind).  Components have their properties.  Board designing capability comprises board design properties for use for Gerber plotting.

Here's an example:
![image](https://github.com/user-attachments/assets/62e7d7a7-2d61-480c-8f4e-23dca58926a1)

**Comment by ubruhin** [comment]
> Well, I tried everything you suggested, but it didn't work...

Did you somehow modify any of your components/devices by manual file operations (copy&paste, text editing)? In this case it wouldn't be surprising that something is messed up, leading in the error messages you posted. But no one should manually modify these files without knowing *exactly* what you're doing (or, live with the consequences of errors).

Or maybe you duplicated our library elements in the library editor and then made breaking changes. The library editor shows a BIG warning if you do that:

![image](https://github.com/user-attachments/assets/cf5a7cfa-80c0-4ee8-bd4b-0f13ef1d790c)

If you ignore this message and save a library element with breaking changes, you shouldn't be surprised by troubles either. The tool warned you so you have to take the consequences.

If you didn't do any of these two cases, the workflow I've posted above works on your system for sure. Just do the same thing what I did and it will work. But if you did strange (dangerous) things, you have to delete all your library elements first.

> So I came up with a new take on ECAD recently, incase you're interested. I called it Easy ECAD.

LibrePCB is easy to use as long as you don't do strange things with it :grin:

**Comment by jv1597** [comment]
Thanks for your comments.  I'm trying out Express PCB right now.  It seems to be pretty close to what I wanted to get my PCBs done.  It has a simple interface and an extensive component library.  I think I'll be sticking to Express PCB for now to see if I can get my boards done with it.  You may close this case if you'd like.  Thanks again for your help.
